import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useLogin } from '../features/auth/hooks';
import { Eye, EyeOff } from 'lucide-react';
export default function LoginPage() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPw, setShowPw] = useState(false);
    const { login, loading } = useLogin();
    function handleSubmit(e) {
        e.preventDefault();
        login(email, password);
    }
    return (_jsxs("div", { className: "min-h-screen flex items-center justify-center px-4 py-12", style: { background: '#0B0B14' }, children: [_jsx("div", { className: "pointer-events-none fixed inset-0 overflow-hidden", children: _jsx("div", { className: "absolute -top-40 left-1/2 -translate-x-1/2 w-[600px] h-[400px] rounded-full opacity-15", style: { background: 'radial-gradient(ellipse, #6B2FD9 0%, transparent 70%)' } }) }), _jsxs("div", { className: "relative z-10 w-full max-w-sm space-y-6", children: [_jsxs("div", { className: "text-center space-y-1", children: [_jsxs("h1", { className: "text-4xl font-bold text-white", style: { fontFamily: "'DM Serif Display', Georgia, serif" }, children: ["Astute", _jsx("span", { style: { color: '#A78BFA' }, children: "IQ" })] }), _jsx("p", { className: "text-slate-500 text-sm", children: "AI-powered compliance review" })] }), _jsxs("div", { className: "rounded-2xl border border-slate-800 bg-[#0f0f1a] p-6 space-y-4 shadow-2xl", children: [_jsx("h2", { className: "text-sm font-semibold text-white mb-4", children: "Sign in to your account" }), _jsxs("form", { onSubmit: handleSubmit, className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "label", children: "Email" }), _jsx("input", { type: "email", className: "input", placeholder: "your@practice.com.au", value: email, onChange: (e) => setEmail(e.target.value), required: true, autoFocus: true })] }), _jsxs("div", { children: [_jsx("label", { className: "label", children: "Password" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: showPw ? 'text' : 'password', className: "input pr-10", placeholder: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022", value: password, onChange: (e) => setPassword(e.target.value), required: true }), _jsx("button", { type: "button", onClick: () => setShowPw((v) => !v), className: "absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors", children: showPw ? _jsx(EyeOff, { size: 15 }) : _jsx(Eye, { size: 15 }) })] })] }), _jsx("div", { className: "flex justify-end", children: _jsx(Link, { to: "/forgot-password", className: "text-xs text-[#A78BFA] hover:text-[#c4b5fd] transition-colors", children: "Forgot password?" }) }), _jsx("button", { type: "submit", disabled: loading, className: "w-full flex items-center justify-center gap-2 py-2.5 rounded-xl font-semibold text-sm text-white transition-all duration-150 disabled:opacity-50", style: {
                                            background: '#6B2FD9',
                                        }, children: loading ? (_jsx("span", { className: "w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" })) : ('Sign in') })] }), _jsxs("p", { className: "text-center text-xs text-slate-500 pt-1", children: ["No account?", ' ', _jsx(Link, { to: "/register", className: "text-[#A78BFA] hover:text-[#c4b5fd] transition-colors", children: "Create one" })] })] }), _jsx("p", { className: "text-center text-xs text-slate-700", children: "Astute Business Partners \u00B7 ISO 27001 certified" })] })] }));
}
